### ISSUE TITLE
Complex tangles on gene graphs

### ISSUE THREAD

**Issue by baozg** [lh3/pangene#1]
Hi, @lh3 

I use `pangene` to run with Arabidopsis pangenome for idenitifing complex gene clusters. But I couldn't really understand why the overall graph is a hairball (also in the HPRC graph Zenodo). In some cases, it seems everything is connected together. 
Do you have any suggestions for this? It could be annotation errors (misannotated gene or transposon elements). I will manually check those nodes and add some filtering steps before building gene graphs.

But human and Arabidopsis annotation should be good enough. Would be possible `pangene` output those "hotspots" for further validation?

<img width="630" alt="image" src="https://github.com/lh3/pangene/assets/20680150/e5d8485b-88b8-4967-a915-655609acad3f">

**Comment by lh3** [comment]
This is caused by a small number of genes that have many paralogs scattered all over in the genome. In human, those include olfactory receptors and ribosome related proteins (e.g. RPL* and RPS*). Generally, I think the more interesting aspect of pangene graphs is those local gene clusters, not the global shapes. I will provide a proper tool to investigate them. Nonetheless, if you want to see a globally cleaner graph, you may 1) let pangene apply more aggressively filtering for example with `-a2 -g5`, or 2) manually filter proteins that are known to have many scattered copies.

**Comment by baozg** [comment]
Thanks for the super fast reply! Excluding those ribosome-related proteins could build a cleaner graph. But olfactory receptors (or some metabolic gene cluster in the plant genomes) are always correlated to adaption, filtering these out before building a graph may lose the chance to explore those gene expansion/contraction activities. Besides those small numbers of genes, I already saw lots of interesting patterns of well-known gene clusters. 

Maybe accepting the reference annotation gff to keep the local synteny (eg. minimum span 3 consecutive genes). But this may hurt the pangene mapping, since the coordinate may come from different individuals. 

Another issue comes from the large diversity of plant genomes, gene fusion and truncation are quite often. Relying on perfect protein mapping (>95%) may lose some signal for those genes. I believe this pattern could also be found in the MHC cluster of primate genomes. Could we use the exon mapping (connected by gene name) for building pangene graphs for more divergent species?

**Comment by lh3** [comment]
Olfactory receptors have many near identical copies all around the human genome. Most genes don't behave like this. We'd better use other approaches to analyze these special genes.

> Maybe accepting the reference annotation gff to keep the local synteny

Panaroo optionally does this I believe. Nonetheless, this would introduce reference biases. I prefer to stay away from such biases.

> minimum span 3 consecutive genes

This wouldn't directly work in gene clusters with frequent gene order or gene copy changes. You would need new heuristics to handle those. This may make the output graph harder to interpret.

> Relying on perfect protein mapping (>95%)

The default cutoff is 50% protein coverage and 50% identity

Overall, a heuristics working best for some corner cases may not be preferred for others. Getting a clean and biologically sound graph is hard. I am grateful for the comments anyway. Thank you.

**Comment by lh3** [comment]
I have implemented a server to visualize pangene graphs. [Here](http://45.55.105.22:8000) is a public server for human genes. Please see the updated README about how to deploying such a server on your machine.

**Comment by baozg** [comment]
Thanks for this amazing tool! The server mode brings the bridge for the interactive exploration of pangene space. That's exactly what I want to ask. I could run the `gfa-server` on my Mac, but I couldn't find way to visualize my gene list. I guess it uses `gfatools` and subset by `view?gene=AMY1A,AMY1B,AMY2A,AMY2B&step=3`? Could it be possible to provide a table (eg. gene name, ref, description in index.html) and visualize it on the server page? What's the difference between step1 and step3?

Would you mind sharing the default graph requirement for this visualization? I already meet the graph size limitation (100kb?), and it requires local gene clusters. For the plotting, sometimes it cannot plot all haplotypes. Such as the following example, it only shows 12 haplotypes, but in other regions `gfa-server` could present all 67 haplotypes.

<img width="502" alt="image" src="https://github.com/lh3/pangene/assets/20680150/b17c7725-f54e-4cff-a84b-14c3ec4ff401">

**Comment by lh3** [comment]
> What's the difference between step1 and step3?

When you specify a gene, you often want to check its nearby genes. "step" controls that. More exactly, with step=3, gfatools does three rounds of BFS to collect nearby genes.

> For the plotting, sometimes it cannot plot all haplotypes.

Unclick "one path per genome" and replot. With this option on, the underlying javascript filters out fragmented genomes that have the list of genes assembled into 2 or more paths. You probably want to play with "merge identical paths" as well.

> Could it be possible to provide a table (eg. gene name, ref, description in index.html) and visualize it on the server page?

You mean you want to do the same like the public server at pangene.liheng.org? That server was deployed with
```sh
./gfa-server -d html -p 80 graph.gfa
```
You put HTML pages in the "html" directory and those will be served at "/" of URL.

**Comment by lh3** [comment]
Also

> I couldn't find way to visualize my gene list.

If you want to show genes to others like pangene.liheng.org, you need to manually create an "index.html" page. You don't need to run gfatools. You just use the server to choose the preferred visualization and keep the link in the HTML page. That is what I did for pangene.liheng.org

**Comment by baozg** [comment]
Thank you so much now I could explore these gene graph

**Comment by baozg** [comment]
Update: I confirmed all the tangles I saw in the Arabidopsis thaliana pangene graph are TE-associated proteins. All the red nodes are the genes detected TE domains.

<img width="794" alt="image" src="https://github.com/lh3/pangene/assets/20680150/782140cb-b101-42b1-8d39-053842118fb3">

**Comment by lh3** [comment]
Are these single-exon genes?

**Comment by baozg** [comment]
Not all of them (16.9% of them are single-exon genes). Chimeras of genes and TEs are quite common in the gene annotation. It could arise from the biological (TE invasive into exon, https://www.science.org/doi/10.1126/science.abc6405 ) / remaining annotation errors (RNA-seq noise, TE masking). We more believe the transcriptome data for gene annotation, but there still expressed TEs or readthrough events (https://www.nature.com/articles/s41467-023-38954-z)

<img width="678" alt="image" src="https://github.com/lh3/pangene/assets/20680150/2e8f303d-a4cd-4fee-8e47-4794390e5237">

**Comment by lh3** [comment]
Do you think it is possible to automatically filter out such genes? Or it would be better for users to filter them before the miniprot alignment?

**Comment by baozg** [comment]
I use TEsorter (https://github.com/zhangrengang/TEsorter) to find these TE-related proteins, it could finish in minutes. But I do think it would be better to leave this choice to users, maybe write Q&A in README. We don't have perfect annotations for any species. Even for model species, we still struggle with gene and TE annotation and Arabidopsis annotation already curated by the community for decades with only one accession. Working with hundreds of different individuals could be more challenging. Furthermore, subgenome/haplotypes of polyploids could introduce more connections in this graph and we don't know how to filter out these (we find only ~50% of genes were shared between tetraploid potato haplotypes). So I totally agree with you, local gene clusters should be the focus of `pangene` graph and it could skip these tangles.
