### ISSUE TITLE
WARNING: skip ##### and failing to pring lines for proteins.faa output

### ISSUE THREAD

**Issue by joanocha** [lh3/pangene#10]
Hello,
I am trying to run the command that prepares the protein fasta as follows:

k8 pangene.js getaa gene-anno.gtf protein-seq.faa > proteins.faa

And I am getting an empty proteins.faa and the error "WARNING: skip "XP_531603.2"

This happens to be the "protein_id" field in my gtf file. I looked into pangene.js and my file has all the fields one would expect in a gtf. The only exception is that there is no "gene_name", only "gene". Would you mind sharing with me the inputs gene-anno.gtf, protein-seq.faa and output proteins.faa? 

Thank you!

**Comment by lh3** [comment]
The script works with gencode and ensembl annotations. It may not work for others. Extracted human proteins are available from zenodo: https://zenodo.org/records/10703141

**Comment by joanocha** [comment]
Thank you for the prompt reply and for this amazing tool. 
I ended up customizing pg_cmd_getaa function and now it works for my gtf as expected.
