### ISSUE TITLE
Genes not included in presence absence matrix

### ISSUE THREAD

**Issue by malearimond** [lh3/pangene#11]
Hello,
I am using pangene to determine the presence and absence of genes across various populations of my model species. 
As recommended I created a pan-gene library and used miniprot to align protein sequences against my assemblies.

Afterwards I used pangene, with parameter setting:

`pangene -e 0.85 -l 0.80 -p 0 -c 40 *.paf > ${output_name}.gfa`

and created a presence absence matrix using: 
`pangene.js gfa2matrix  ${output_name}.gfa > ${output_name}.Rtab`

However, upon checking the PAF files and the corresponding PAV matrix, I noticed that some genes were not included in the matrix, even though their identity in the PAF file was greater than 85% and fraction aligned >80%. I have attached an example of one such gene for your reference.

![Screenshot 2024-09-09 150850](https://github.com/user-attachments/assets/bf8699fa-fa92-4ba4-9870-0d6bfbc30cf6)

(First command is the paf file, second the matrix for the same accession).

Could you please help me understand why this might be happening? Have I possibly overlooked something?

Thank you in advance for your assistance!

Best regards,
Male

**Comment by lh3** [comment]
There may be genes mapped better at the loci.
