### ISSUE TITLE
Clarification on Interpretation of Genes with Empty Fill

### ISSUE THREAD

**Issue by Evenlyeven** [lh3/pangene#12]
Thanks for the tool!

I had a hard time interpreting the gene with empty fill, like **gene 001883909** in my case (top), and the **gorilla LRRC37A3** in the pangene paper (bottom). Does the empty fill indicate a gene deletion, or is there another explanation?

Any clarification would be greatly appreciated!

![image](https://github.com/user-attachments/assets/3b981029-217c-46ed-bdd5-d61d0fc42bf7)
![image](https://github.com/user-attachments/assets/5afc4da1-d610-4522-aa7e-bce1838b9007)

**Comment by lh3** [comment]
See figure legend:

> The LRRC37A3 alignment in gorilla has two in-frame stop codons

An empty box indicates in-frame stop codons or frameshifts in alignment.
