### ISSUE TITLE
I didn't get the html files, please help me

### ISSUE THREAD

**Issue by Djangodu** [lh3/pangene#13]
Hello, @lh3,

I have successfully processed 11 animal genome .fna files, each averaging around 2.8GB in size, following the instructions outlined in the README.md. I have also obtained protein sequences from NCBI, totaling 42,653 entries in the protein.faa file. After aligning these proteins to the genomes, I generated 11 pfa files, averaging 9.7MB each. Subsequently, constructing the pangenome graphs resulted in a .gfa file of 9.48MB. Additionally, the bubble.txt file is 691KB in size.

I would like to verify if the sizes of the files I have obtained are within the expected range. Furthermore, I have a question regarding the bubble.txt file: could you please clarify what the size variations in the genome bubbles signify?

Regarding the visualization process, I have attempted to set up the server using the following commands:

```
curl -L https://github.com/lh3/pangene/releases/download/v1.1/pangene-1.1-bin.tar.bz2 | tar -jxf -
cd pangene-1.1-bin
bin_arm64-mac/gfa-server -d html data/*.gfa.gz 2> server.log # for Mac
```

However, I am not seeing any output in the html directory. Could you please provide guidance on why this might be the case and how I can resolve this issue?

Thank you for your assistance.

**Comment by lh3** [comment]
gfa-server read HTML, not write HTML.
