### ISSUE TITLE
Questions about the result of the drawing

### ISSUE THREAD

**Issue by Fight-a-tiger-in-the-mountain** [lh3/pangene#14]
Hello, Teacher Li, I went through your process, but I noticed that some genes in the results are hollow. I don't know enough to understand why these genes are hollow, but I think since they are different from others, there must be a reason, I hope you can give me some advice

![0E1E9207FA3431D43CE3EA144CE3C90F](https://github.com/user-attachments/assets/1e6c4aec-99ea-4a17-9082-cb27264744b7)

**Comment by lh3** [comment]
See instruction on the "/view" page: "An empty arrow suggests frameshifts or in-frame stop codons".

**Comment by Fight-a-tiger-in-the-mountain** [comment]
收到
