### ISSUE TITLE
When I run pangene.js, I met error: SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by kuangzhuoran** [lh3/pangene#16]
my command is : k8 pangene.js call graph.gfa > bubble.txt
And I met:

pangene.js:9: SyntaxError: Unexpected identifier
        for (let j = i; j < this.length - 1; ++j)
          ^
SyntaxError: Unexpected identifier

**Comment by kuangzhuoran** [comment]
Sorry, this issue has been solved

**Comment by kuangzhuoran** [comment]
https://github.com/lh3/pangene/issues/7

**Comment by Dorjeetashi** [comment]
Can you tell me how to solve this problem? I also encountered the same problem

**Comment by lh3** [comment]
See #7
