### ISSUE TITLE
How to visualize the results on windows or Cluster

### ISSUE THREAD

**Issue by kuangzhuoran** [lh3/pangene#17]
Hi !
My command is : bin_x64-linux/gfa-server -d html graph.gfa 
And then it stucked

$ bin_x64-linux/gfa-server -d html graph.gfa              
[1729961415787277064] read graph 'graph' from '/data/01/user164/workspace_for_whole_object/spalax_chrSV/40.pangene/2.deal/addfenshu/graph.gfa'
[1729961415985434154] server started at /view

**Comment by lh3** [comment]
See [README](https://github.com/lh3/pangene?tab=readme-ov-file#graph-visualization).

**Comment by kuangzhuoran** [comment]
Thanks for your reply.
I borrowed a Mac computer and entered the corresponding command in the terminal (bin_arm64-mac/gfa-server -d html data/*.gfa.gz 2> server.log # for Mac). 
However, when I tried to open the link http://127.0.0.1:8000/ using various browsers, it showed a 404 error.

**Comment by QianghuiZhu** [comment]
hi, do you solve this problem? I also meet 404 error while using gfa-server. But there was not any error at previous processes.
I could use the test data without any error, but when using my own data, 404 error will appear.
