### ISSUE TITLE
Something wrong when I use pangene‘s code

### ISSUE THREAD

**Issue by Fight-a-tiger-in-the-mountain** [lh3/pangene#7]
Hello Professor Li, I have some problems when running with the code you presented. The problems are as follows:

$k8 ~/software/pangene-1.1/pangene.js getaa 00.data/genomic.gtf 00.data/protein.faa > 01.pro_align/proteins.faa
/storage/public/home/2022060223/software/pangene-1.1/pangene.js:9: SyntaxError: Unexpected identifier
	for (let j = i; j < this.length - 1; ++j)
          ^
SyntaxError: Unexpected identifier

I checked what seems to be the problem with this file pangen.js? In order to check whether there is a problem with the k8 version, I used node to run, and the results are as follows:

$node ~/software/pangene-1.1/pangene.js getaa 00.data/genomic.gtf 00.data/protein.faa > 01.pro_align/proteins.faa
/storage/public/home/2022060223/software/pangene-1.1/pangene.js:1349
	var cmd = args.shift();
	               ^

TypeError: args.shift is not a function
    at main (/storage/public/home/2022060223/software/pangene-1.1/pangene.js:1349:17)
    at Object.<anonymous> (/storage/public/home/2022060223/software/pangene-1.1/pangene.js:1363:1)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.12.2

I'm not sure why, but it looks like there's something wrong with the pangene-1.1 script, but I'm not sure.

Hope to get your reply, thank you!

**Comment by lh3** [comment]
You need to use k8 v1.0. Node or older k8 wouldn't work.

**Comment by Fight-a-tiger-in-the-mountain** [comment]
收到

**Comment by Fight-a-tiger-in-the-mountain** [comment]
Your 1.0 version of k8 requires v8 to be installed, but requires that the location of v8 be fixed to... /, manual installation of v8 requires google's depot_tools, which is difficult to verify file integrity when not connected to the Internet (not easy to install, always missing files), so I hope you can share the latest version of k8 files to conda?

As a novice thank you for your contribution to scientific research and care for the novice!
