### ISSUE TITLE
I've had some problems running in other species

### ISSUE THREAD

**Issue by Fight-a-tiger-in-the-mountain** [lh3/pangene#9]
Hello Professor Li, I have deployed the server locally according to your process, as shown in the picture below
![{{9OCS)76(H6OL%4C_KST7I](https://github.com/lh3/pangene/assets/136800252/87c94fc4-9d73-493d-bfa4-6de9649737f2)
After I opened the web page locally, I got the information as shown in the following picture, which is the content of the previous gfa file.
![(YU{3~DLLIV2EYXISJYDKBX](https://github.com/lh3/pangene/assets/136800252/305b5a9c-d4c4-45d8-af15-df44e3d725b7)
![XASP$}2(V9O)Y88PBG@HKND](https://github.com/lh3/pangene/assets/136800252/722d5318-d182-4229-9a31-547e1f7caa08)

I didn't get a picture when I searched for some genes. I don't know why
I tried a lot of genes and didn't see any pangenegraph, whereas typing any gene into your website will bring up a picture
(This is my analysis from other species following your process) the genes may be different, I hope you can shed some light
Here is your web interface
![UXKQCLC7J{90YF1DV%VW~FX](https://github.com/lh3/pangene/assets/136800252/53ec88e2-42ed-480f-9f24-115e7209e9db)
Thank you very much

**Comment by Evenlyeven** [comment]
I am experiencing the same issue. Have you figured out why? Thanks!

**Comment by Fight-a-tiger-in-the-mountain** [comment]
收到

**Comment by lh3** [comment]
You may uncheck "filter fragmented contigs" and try again.

**Comment by Evenlyeven** [comment]
> You may uncheck "filter fragmented contigs" and try again.


<br>

Thank you for looking it this! I tried it, there's still no plot. Attached is the test `MT.gfa` file from `gfatools`.  

<br>
<br>



![image](https://github.com/user-attachments/assets/f5d27252-8d61-4450-a4b3-447f2a8f294c)

**Comment by lh3** [comment]
I see the issue. You need to run it in the "pangene-1.1-bin" directory as the README shows:
```sh
# Deploy the GFA server on the C4 example; require pangene-1.1-bin
cd pangene-1.1-bin                         # run gfa-server in this directory
bin_arm64-mac/gfa-server /path/to/C4.gfa   # or use bin_linux-x64 on x64-linux
```
Also, gfa-server is developed for pangene graphs and won't plot anything for MT.gfa anyway.
